from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('order-wizard/', views.OrderWizardView.as_view(), name='order_wizard'),
    path('api/order/save/', views.save_order_data, name='save_order_data'),
    path('api/order/submit/', views.submit_order, name='submit_order'),
    path('order/confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('menu/', views.menu, name='menu'),
    path('services/', views.services, name='services'),
    path('contacts/', views.contacts, name='contacts'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.about_view, name='about'),
    path('calculator/', views.calculator, name='calculator'),
    path('orders/', views.orders, name='orders'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('order/success/', views.order_success, name='order_success'),
   
    # Личный кабинет
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<str:item_type>/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('cart/update/service/<int:service_id>/', views.update_cart_service, name='update_cart_service'),
    path('cart/remove/<str:item_type>/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('workers/', views.WorkerListView.as_view(), name='worker_list'),
    path('workers/<int:pk>/', views.WorkerDetailView.as_view(), name='worker_detail'),
    path('workers/create/', views.WorkerCreateView.as_view(), name='worker_create'),
    path('workers/<int:pk>/update/', views.WorkerUpdateView.as_view(), name='worker_update'),
    path('workers/<int:pk>/delete/', views.WorkerDeleteView.as_view(), name='worker_delete'),
    path('orders/<int:order_id>/assign-workers/', views.assign_workers_to_order, name='assign_workers'),
    path('orders/remove-worker/<int:assignment_id>/', views.remove_worker_from_order, name='remove_worker'),
    path('worker/orders/', views.WorkerOrdersView.as_view(), name='worker_orders'),
    path('orders/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),
    path('worker/schedule/', views.WorkerScheduleView.as_view(), name='worker_schedule'),
    path('worker/schedule/create/', views.WorkerScheduleCreateView.as_view(), name='worker_schedule_create'),
    path('worker/schedule/<int:pk>/update/', views.WorkerScheduleUpdateView.as_view(), name='worker_schedule_update'),
    path('worker/schedule/<int:pk>/delete/', views.WorkerScheduleDeleteView.as_view(), name='worker_schedule_delete'),
    path('worker/schedule/calendar/', views.WorkerScheduleCalendarView.as_view(), name='worker_schedule_calendar'),
    path('contact-form/', views.contact_form, name='contact_form'),
] 