# Generated by Django 5.2.1 on 2025-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес мероприятия'),
            preserve_default=False,
        ),
    ]
